.TH yoga-image-optimizer 1 "" "version {VERSION}" "YOGA IMAGE OPTIMIZER"

.SH NAME
YOGA Image Optimizer - Convert and optimize images

.SH SYNOPSIS
.B yoga-image-optimizer
.I [IMAGE_FILE_1 [IMAGE_FILE_2 [...]]]

.SH DESCRIPTION
{DESCRIPTION}

.SH WEB SITE
{WEBSITE}

.SH AUTHOR
Fabien Loison <https://flozz.fr/>

.SH REPORTING BUGS
Report bugs to <https://github.com/flozz/yoga-image-optimizer/issues>.

.SH COPYRIGHT
Copyright  ©  2021 Fabien Loison

YOGA Image Optimizer is free software under GNU GPL v3+ licence
<http://gnu.org/licenses/gpl.html>, you are free to modify and redistribute it
under the terms of the license.


